// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtflzvuhfvkvftjhyqay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0Zmx6dnVoZnZrdmZ0amh5cWF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3NTg1MDYsImV4cCI6MjA1NDMzNDUwNn0.b06q8JGR5Ntw0yKP9SMI5zPgLPT0x6lfUuqAL42BZeg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);